# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.TextField()),
                ('deny', models.TextField()),
                ('allow_domains', models.TextField()),
                ('deny_domains', models.TextField()),
                ('deny_extensions', models.TextField()),
                ('restrict_xpaths', models.TextField()),
                ('restrict_css', models.TextField()),
                ('tags', models.TextField()),
                ('attrs', models.TextField()),
                ('canonicalize', models.IntegerField(default=1)),
                ('unique', models.IntegerField(default=1)),
                ('process_value', models.CharField(max_length=255)),
                ('callback', models.CharField(max_length=255)),
                ('cb_kwargs', models.TextField()),
                ('follow', models.IntegerField(default=0)),
                ('process_links', models.CharField(max_length=255)),
                ('process_request', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allowed_domains', models.TextField()),
                ('start_urls', models.TextField()),
                ('custom_settings', models.TextField()),
                ('crawler', models.TextField()),
                ('settings', models.TextField()),
                ('logger', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spider'),
        ),
    ]
